function allowable_labels = get_allowable_elecs


%% get allowable electrodes
allow_nums = num2cell(repmat((1:12)',6,1));
allow_lr = [repmat({'L'},12*3,1);...
    repmat({'R'},12*3,1)];
allow_letters = [repmat({'A'},12,1);...
    repmat({'B'},12,1);...
    repmat({'C'},12,1);...
    repmat({'A'},12,1);...
    repmat({'B'},12,1);...
    repmat({'C'},12,1)];
allowable_labels = cellfun(@(x,y,z) ...
    sprintf('%s%s%d',x,y,z),allow_lr,allow_letters,...
    allow_nums,'Uniformoutput',false);

end